### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rulenine** [Valheim-Modding/Jotunn#377] opened 2022-11-05 23:59 UTC
Details:
Jotunn Version: Latest version
Jotunn Submodule(if applicable):
Repeatability(Consistent(100%), Inconsistent(50%), Rare(1%), Unknown(==1)): 100%

**Problem Description:**
Client cannot connect to server. Server Sync issue. Server Sync Fix mod used to resolve and problem remains with specific Jotunn mention as the problem. Was working fine until a server update was done. Cannot roll back server (valheim does not support launching old versions as far as I can tell, at least not for dedicated servers)

**Expected Behaviour:**
Client should be able to connect to server. All versions of mods and game are identical. Enforce mod is on.

**Actual Behaviour:**
Client cannot connect.

**Link to your server's and client's LogOutput.log**
`Exception in ZRpc::HandlePackage: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: VTable setup of type Jotunn.Managers.SynchronizationManager+PeerInfoBlockingSocket failedat Jotunn.Managers.SynchronizationManager+Patches.ZNet_RPC_Pre_PeerInfo (ZNet __instance, ZRpc rpc, Jotunn.Managers.SynchronizationManager+PeerInfoBlockingSocket& __state) [0x00005] in `<a8e60cfb46b3438eb8339d0b89fd1a8d>:0``

**Comment by sirskunkalot** [comment] 2022-11-06 00:31
Can you join the Jötunn discord and post your full log there?
https://discord.gg/DdUt6g7gyA

**Comment by MSchmoecker** [comment] 2022-11-07 17:24
This most likely means you have an old Jotunn version installed. With the current Valheim release (0.211.11) at least Jotunn 2.8.0 has to be used, while the most recent release (2.9.0) is recommended

**Comment by MSchmoecker** [comment] 2022-11-16 10:53
Going to close this, as it is caused by an outdated Jotunn install.

If you still have problems, please post your full client and server log (from `BepInEx/LogOutput.log`) here or at Discord.

**Closed as completed** 2022-11-16 10:53 UTC
