### ISSUE TITLE
Add unified configuration management and sync

### ISSUE THREAD

**Issue by sirskunkalot** [Valheim-Modding/Jotunn#34] opened 2021-04-03 23:19 UTC
Add an API for mod configs. Sync & GUI code can be transferred from https://github.com/sirskunkalot/Veilheim

**Comment by paddywaan** [comment] 2021-04-04 08:16
Is duplicate of: https://github.com/Valheim-Modding/Jotunn/issues/25

**Closed as completed by paddywaan** 2021-04-04 08:16 UTC
Labels: enhancement
