### ISSUE TITLE
[BUG] Incompatible version when using dedicated server on Linux host

### ISSUE THREAD

**Issue by jordan2718** [Valheim-Modding/Jotunn#436] opened 2024-09-26 07:37 UTC
Details: Mod version check fails, shows server has not loaded mods using Jotunn
Jotunn Version: 2.20.3
Jotunn Submodule(if applicable):
Repeatability(Consistent(100%), Inconsistent(50%), Rare(1%), Unknown(==1)): 100%

**Problem Description:**
I run Valheim dedicated server from a Linux server running AMP. When installing a mod that uses Jotunn the mod doesn't load however in the logs I do see the lines to say the mods are loading. When connecting to the server I get the version mismatch error. I have tested with using both container and non container versions in AMP and also with the docker container on UnRAID (which has worked for me in the past with these same mods but not since the latest Valheim update). As a test I did try running a dedicated server from Steam on my Windows client PC and it works from there without issue so seems to not work with any of the Linux versions. I have uploaded logs from both the windows and Linux connections.

**Expected Behaviour:**
Came should connect as versions do match and log shows mods have been loaded.

**Actual Behaviour:**
version mismatch showing mods not loaded on server

Files have been uploaded to the below links. Included are 2 client log files from the same machine, one connecting to the windows based server and the other connecting to the linux based server. 2 screenshots, one showing the error in game and another with a snip from the console output on the linux server that I think could be related to the issue (I don't see this error on the windows console). Last 2 files are the logs from the 2 servers.
[Client - LogOutput - windows.log](https://github.com/user-attachments/files/17144544/Client.-.LogOutput.-.windows.log)
[Client - LogOutput-Linux.log](https://github.com/user-attachments/files/17144545/Client.-.LogOutput-Linux.log)
![Screenshot 2024-09-26 080948](https://github.com/user-attachments/assets/c5ba8748-eff2-4f57-8ce2-f67c29ba56f2)
![Screenshot 2024-09-26 081107](https://github.com/user-attachments/assets/74052357-1bad-444e-89d4-af45288b9bfc)
[Server - LogOutput - Windows.log](https://github.com/user-attachments/files/17144546/Server.-.LogOutput.-.Windows.log)
[Server - LogOutput-Linux.log](https://github.com/user-attachments/files/17144547/Server.-.LogOutput-Linux.log)

**Comment by MSchmoecker** [comment] 2024-09-27 20:38
Can you try to disable Better Networking or disable the compression? The version package from the client could not be deserialized properly on the server, so this sounds like the most likely conflict

**Comment by jordan2718** [comment] 2024-09-27 21:58
Thanks, I did try without that and it still didn't work but took your advice that it is likely a conflict and removed all but XPortal and ExpertExplorers. The issue still remained. I removed ExpertExplorers and the issue resolved. I'll raise an issue on the ExpertExplorers page. Looking at the change log that mod has has version identity issues in the past so could be an issue again. Thanks for the help 👍

**Comment by MSchmoecker** [comment] 2024-10-05 20:07
Found the root cause: https://github.com/MysteriousMilk/ExpertExplorer/blob/44d758818830d435ecaa18d8e7a3b239fed6ca91/ExpertExplorer/ExpertExplorer.cs#L24, the ExpertExplorer mod is only specifying two version digits instead of three. BepInEx handles this fine but Jotunn does not. Will reopen until fixed in Jotunn

**Comment by MSchmoecker** [comment] 2024-10-16 06:47
Fixed in 24b426be39bc460b037a7ba92a9e59e452b49380, will be released with the 2.21.0 update

**Comment by MSchmoecker** [comment] 2024-10-20 12:47
Fixed in 2.21.0

**Closed as completed by MSchmoecker** 2024-10-20 12:47 UTC

**Comment by MysteriousMilk** [comment] 2024-10-21 15:22
@MSchmoecker Starting with this version of Jotunn (2.21.0) only two digits will be required? That would be great, as I messed up on the last release of ExpertExplorer and didn't put the trailing 0. I don't think it was the first time I've done that either.

**Comment by MSchmoecker** [comment] 2024-10-21 15:33
yes, both `X.Y` as well as `X.Y.Z` version formats are supported now
